services:
  - type: web
    name: chisel-frankfurt    
    runtime: image
    image:
      url: docker.io/jpillora/chisel:1.7.6
    dockerCommand: /app/bin server --socks5 --reverse
    region: frankfurt
    plan: free
    envVars:
      - key: AUTH
        sync: false

  # Расскомментируйте ниже для деплоя нескольких серверов (и соответственно прокси)
  # На практике оптимальная скорость - в локации Франкфурт описанной выше (для РФ)
  # - type: web
  #   name: chisel-oregon    
  #   runtime: image
  #   image:
  #     url: docker.io/jpillora/chisel:1.7.6
  #   dockerCommand: /app/bin server --socks5 --reverse
  #   region: oregon
  #   plan: free
  #   envVars:
  #     - key: AUTH
  #       sync: false
  # - type: web
  #   name: chisel-server-ohio    
  #   runtime: image
  #   image:
  #     url: docker.io/jpillora/chisel:1.7.6
  #   dockerCommand: /app/bin server --socks5 --reverse
  #   region: ohio
  #   plan: free
  #   envVars:
  #     - key: AUTH
  #       sync: false
  # - type: web
  #   name: chisel-singapore    
  #   runtime: image
  #   image:
  #     url: docker.io/jpillora/chisel:1.7.6
  #   dockerCommand: /app/bin server --socks5 --reverse
  #   region: singapore
  #   plan: free
  #   envVars:
  #     - key: AUTH
  #       sync: false